version: "3"

services:
  mysql:
    restart: always
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: account
    volumes:
      - ./scripts/mysql:/docker-entrypoint-initdb.d
  mongo:
    restart: on-failure
    image: mongo:3.6.3
    environment:
      - MONGO_INITDB_DATABASE=account
    volumes:
      - ./scripts/mongo:/docker-entrypoint-initdb.d
    ports:
      - 27018:27017

